---@diagnostic disable: undefined-global
local util = require("neotest-cypress.util")

describe("util", function()
  it("creates position IDs correctly", function()
    local id = util.create_position_id("file.cy.ts", {"suite1", "test1"})
    assert.equals("file.cy.ts::suite1::test1", id)
  end)

  it("extracts test name from position ID", function()
    local name = util.get_test_name_from_id("file.cy.ts::suite::test")
    assert.equals("test", name)
  end)

  it("gets namespace path from position ID", function()
    local namespaces = util.get_namespace_path("file.cy.ts::a::b::test")
    assert.same({"a", "b"}, namespaces)
  end)

  it("safely calls functions", function()
    local result = util.safe_call(function() return "ok" end)
    assert.equals("ok", result)
  end)

  it("escapes regex special characters in grep pattern", function()
    assert.equals("test \\(with parens\\)", util.escape_grep_pattern("test (with parens)"))
    assert.equals("test\\.name", util.escape_grep_pattern("test.name"))
    assert.equals("test\\?", util.escape_grep_pattern("test?"))
    assert.equals("test\\*", util.escape_grep_pattern("test*"))
    assert.equals("test\\+", util.escape_grep_pattern("test+"))
    assert.equals("test\\-", util.escape_grep_pattern("test-"))
    assert.equals("test\\[", util.escape_grep_pattern("test["))
    assert.equals("test\\]", util.escape_grep_pattern("test]"))
    assert.equals("test\\^", util.escape_grep_pattern("test^"))
    assert.equals("test\\$", util.escape_grep_pattern("test$"))
  end)

  it("leaves normal strings unchanged", function()
    assert.equals("should pass", util.escape_grep_pattern("should pass"))
    assert.equals("test name with spaces", util.escape_grep_pattern("test name with spaces"))
    assert.equals("test123", util.escape_grep_pattern("test123"))
  end)
end)
